sudo: required

services:
  - docker

before_install:
  - docker pull commonsearch/local-elasticsearch
  - docker run -d -p 127.0.0.1:39200:9200 -p 127.0.0.1:39300:9300 commonsearch/local-elasticsearch
  - docker pull commonsearch/local-back
  - docker ps
  - docker info
  - docker version
  - ps -ef
  - netstat -lpn
  - curl "http://127.0.0.1:39200"
  - docker run commonsearch/local-back curl "http://127.0.0.1:39200"

script:
  - make docker_test
